
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ILHAM
 */
public class FrameJodoh extends javax.swing.JFrame {

    /**
     * Creates new form FrameJodoh
     */
    public FrameJodoh() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        goldar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        bini = new javax.swing.JRadioButton();
        laki = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Jenis Kelamin");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 230, 100, 20);

        jLabel3.setText("Nama Anda");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Hasil");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 310, 60, 40);

        hasil.setEditable(false);
        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 370, 310, 100);

        jButton3.setText("COBA LAGI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 490, 110, 30);

        goldar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));
        goldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goldarActionPerformed(evt);
            }
        });
        getContentPane().add(goldar);
        goldar.setBounds(130, 160, 60, 40);

        jButton1.setText("SELESAI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 260, 80, 30);
        getContentPane().add(nama);
        nama.setBounds(130, 100, 180, 40);

        buttonGroup1.add(bini);
        bini.setText("Perempuan");
        bini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biniActionPerformed(evt);
            }
        });
        getContentPane().add(bini);
        bini.setBounds(230, 230, 90, 23);

        buttonGroup1.add(laki);
        laki.setText("Laki - Laki");
        laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiActionPerformed(evt);
            }
        });
        getContentPane().add(laki);
        laki.setBounds(130, 230, 90, 23);

        jLabel5.setText("Golongan Darah");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 170, 100, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("JUST FOR FUN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 40, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("CEK JODOH");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 10, 130, 40);

        setBounds(0, 0, 384, 586);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:  
        hasil.setText("");
        nama.setText("");
        buttonGroup1.clearSelection();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void goldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goldarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_goldarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String badi []= {"Mimi Peri","Dijjah Yellow","Awkarin","Selena Gomez"};
        String bidi []= {"SOLEH","SALEM","BIKANG","KENCUR"};
        String Nama = nama.getText();
        String darah = goldar.getSelectedItem().toString();
        
        if (laki.isSelected()){
        if(goldar.getSelectedItem().equals("A")){
            hasil.setText(Nama+" Golongan Darah Anda Adalah "+darah+"\n\n"+"Anda Cocok Bersanding Dengan "+badi[0]);
        }
        else if(goldar.getSelectedItem().equals("B")){
            hasil.setText(Nama+" Golongan Darah Anda Adalah "+darah+"\n\n"+"Anda Cocok Bersanding Dengan "+badi[1]);
        }
        else if(goldar.getSelectedItem().equals("AB")){
            hasil.setText(Nama+" Golongan Darah Anda Adalah "+darah+"\n\n"+"Anda Cocok Bersanding Dengan "+badi[2]);
        }
        else {
            hasil.setText(Nama+" Golongan Darah Anda Adalah "+darah+"\n\n"+"Anda Cocok Bersanding Dengan "+badi[3]);
        }
        }
        else{
        if(goldar.getSelectedItem().equals("A")){
            hasil.setText(Nama+" Golongan Darah Anda Adalah "+darah+"\n\n"+"Anda Cocok Bersanding Dengan "+bidi[0]);
        }
        else if(goldar.getSelectedItem().equals("B")){
            hasil.setText(Nama+" Golongan Darah Anda Adalah "+darah+"\n\n"+"Anda Cocok Bersanding Dengan "+bidi[1]);
        }
        else if(goldar.getSelectedItem().equals("AB")){
            hasil.setText(Nama+" Golongan Darah Anda Adalah "+darah+"\n\n"+"Anda Cocok Bersanding Dengan "+bidi[2]);
        }
        else {
            hasil.setText(Nama+" Golongan Darah Anda Adalah "+darah+"\n\n"+"Anda Cocok Bersanding Dengan "+bidi[3]);
        }
        }
        if (nama.getText().equals(""))
            {
                hasil.setText("");
                JOptionPane.showMessageDialog(null, "Nama Belum Diisi");   
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiActionPerformed

    private void biniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameJodoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameJodoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameJodoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameJodoh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameJodoh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bini;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> goldar;
    private javax.swing.JTextArea hasil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    // End of variables declaration//GEN-END:variables
}
